[package]
name = "ivy-priority-fee"
version = "0.1.0"
edition = "2024"

[dependencies]
rouille = "3.6.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
ureq = { version = "2.12.1", features = ["json"] }
